# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(20, 60, 391, 281))
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 410, 274, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lengthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lengthLabel.setObjectName("lengthLabel")
        self.gridLayout.addWidget(self.lengthLabel, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.lengthLabel_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lengthLabel_3.setObjectName("lengthLabel_3")
        self.gridLayout.addWidget(self.lengthLabel_3, 1, 0, 1, 1)
        self.lengthLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lengthLabel_2.setObjectName("lengthLabel_2")
        self.gridLayout.addWidget(self.lengthLabel_2, 0, 0, 1, 1)
        self.pressureLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pressureLabel.setObjectName("pressureLabel")
        self.gridLayout.addWidget(self.pressureLabel, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.agLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.agLabel.setObjectName("agLabel")
        self.gridLayout.addWidget(self.agLabel, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(420, 60, 301, 411))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lengthGraphWidget = RealTimePlotWidget(self.gridLayoutWidget_2)
        self.lengthGraphWidget.setObjectName("lengthGraphWidget")
        self.gridLayout_2.addWidget(self.lengthGraphWidget, 2, 0, 1, 1)
        self.pressureGraphWidget = RealTimePlotWidget(self.gridLayoutWidget_2)
        self.pressureGraphWidget.setObjectName("pressureGraphWidget")
        self.gridLayout_2.addWidget(self.pressureGraphWidget, 1, 0, 1, 1)
        self.curveFittingGraphWidget = TwoLineRealTimePlotWidget(self.gridLayoutWidget_2)
        self.curveFittingGraphWidget.setObjectName("curveFittingGraphWidget")
        self.gridLayout_2.addWidget(self.curveFittingGraphWidget, 3, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 340, 390, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.pauseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout.addWidget(self.pauseButton)
        self.stopButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.configButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.configButton.setObjectName("configButton")
        self.horizontalLayout.addWidget(self.configButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.imageLabel.setText(_translate("MainWindow", "imageLabel"))
        self.lengthLabel.setText(_translate("MainWindow", "lengthLabel"))
        self.label.setText(_translate("MainWindow", " e-6m"))
        self.label_2.setText(_translate("MainWindow", "in H2O"))
        self.lengthLabel_3.setText(_translate("MainWindow", "Pressure inH2O"))
        self.lengthLabel_2.setText(_translate("MainWindow", "Protrusion Length"))
        self.pressureLabel.setText(_translate("MainWindow", "pressureLabel"))
        self.label_3.setText(_translate("MainWindow", "Ag"))
        self.agLabel.setText(_translate("MainWindow", "agLabel"))
        self.label_4.setText(_translate("MainWindow", "(Unit)"))
        self.startButton.setText(_translate("MainWindow", "START"))
        self.pauseButton.setText(_translate("MainWindow", "PAUSE"))
        self.stopButton.setText(_translate("MainWindow", "STOP"))
        self.configButton.setText(_translate("MainWindow", "CONFIG"))
from views.realTimePlotWidget import RealTimePlotWidget
from views.twoLineRealTimePlotWidget import TwoLineRealTimePlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
